### ISSUE TITLE
29

### ISSUE THREAD

**Issue by KarelSvo** [cedricp/ecutweaker#1]
https://github.com/cedricp/ecutweaker/commit/75d191262f480b09d3fbfe0dde92e167affad943

https://github.com/cedricp/ecutweaker/blob/master/EcuTweaker/src/main/java/org/quark/dr/canapp/ElmBase.java

Many 29 bit addresses and vehicle types with 29 bit ecus added, but no 29 bit and STN support

**Comment by Furtif** [comment]
@KarelSvo look pr if good.

**Comment by KarelSvo** [comment]
Thanks for the quick response, looks good. Finally the ecutweaker becomes a good alternative to PyDDT.

I want to build an app with an integrated database.
Where does the ecu.zip have to be positioned so that it is recognized?
And does a path need to be changed? If yes, at what file?

**Comment by Furtif** [comment]
> Thanks for the quick response, looks good. Finally the ecutweaker becomes a good alternative to PyDDT.
> 
> I want to build an app with an integrated database. Where does the ecu.zip have to be positioned so that it is recognized? And does a path need to be changed? If yes, at what file? The app should only work with the integrated database.

Place ecu.zip (the same for ddt4all) in root IntenalStorage android.

**Comment by KarelSvo** [comment]
That means next to scr/main?
https://github.com/cedricp/ecutweaker/tree/master/EcuTweaker

**Comment by Furtif** [comment]
> That means next to scr/main? https://github.com/cedricp/ecutweaker/tree/master/EcuTweaker

i need merge pr for good changes in master. go make it.

**Comment by Furtif** [comment]
if i merge this issue is auto closed, if you want test before uses this branch https://github.com/cedricp/ecutweaker/tree/fix_29bits

**Comment by Furtif** [comment]
@KarelSvo https://github.com/cedricp/ecutweaker/pull/2#issuecomment-1893515066

Cedric says need test for now I can't, are you testing this? tell results please. Thanks

**Comment by KarelSvo** [comment]
https://github.com/cedricp/ecutweaker/blob/master/ecu/src/main/java/org/quark/dr/ecu/EcuDatabase.java#L263

I'll test when I figure out what needs to be written in this file to just access an internal ecu.zip.
And where the ecu.zip can best be placed.
I would like to build a version reduced to a few vehicle types, with some ECU screens i created in the ddt Builder itself.
Since I'm not a programmer, I can only change and test and hope that it works.
And this takes a long time, if no competent help is available.

**Comment by Furtif** [comment]
> https://github.com/cedricp/ecutweaker/blob/master/ecu/src/main/java/org/quark/dr/ecu/EcuDatabase.java#L263
> 
> I'll test when I figure out what needs to be written in this file to just access an internal ecu.zip. And where the ecu.zip can best be placed. I would like to build a version reduced to a few vehicle types, with some ECU screens i created in the ddt Builder itself. Since I'm not a programmer, I can only change and test and hope that it works. And this takes a long time, if no competent help is available.

I already told you where to put the ecu.zip but put it at the root internal storage.

**Comment by Furtif** [comment]
For versions reduced to certain cars, in future versions this will load the cars and addresses from projects.json, just edit the json with what you want.

**Comment by Furtif** [comment]
for example only Dacia wants to recreate the ecu.zip only with dacia removes from projects.json all that are not Dacia.

but well, this is not using json yet, I just put the file in the source for ref's https://github.com/cedricp/ecutweaker/blob/master/EcuTweaker/src/main/java/org/quark/dr/canapp/Projects.java#L5

**Comment by KarelSvo** [comment]
Since I don't know what exactly is called "root internal storage", I asked if that was next to src/main. https://github.com/cedricp/ecutweaker/tree/master/EcuTweaker


I also don't know if an internal ecu.zip is "turned off" by an externally added ecu.zip.


I had edited this vehicle list but had not yet checked the change https://github.com/cedricp/ecutweaker/blob/master/ecu/src/main/java/org/quark/dr/ecu/EcuDatabase.java#L35

**Comment by Furtif** [comment]
Yes, for the moment the apk is using this Dict or var but in the future it will load the json and use what is in the json, just like I did in the python version

**Comment by KarelSvo** [comment]
The insert the ecu.zip  in the ecutweaker-master is not included in the apk during the build in Android Studio.

**Comment by KarelSvo** [comment]
ecu.zip is now in the resources folder and will be inserted into the app when building.
However, ecu.zip is not found by the installed app.
I don't know how to define the path to this folder.

**Comment by cedricp** [comment]
the zip can be everywhere on the android storage (and must not be extracted!), the app should find it automatically. Try to put it in your download folder for example. Don't forget to give read permission to the app.

**Comment by cedricp** [comment]
Forgot to sat that yo must generate it with DDT4All.

**Comment by KarelSvo** [comment]
@cedricp 
Integrating an external ecu.zip works.

I would like to embed a small (25MB) ecu.zip into the app, but I don't know what needs to be written for the app to find the internal ecu.zip.
