### ISSUE TITLE
ECU communication error

### ISSUE THREAD

**Issue by alex-military** [cedricp/ecutweaker#10]
Hi, I have a Sandero Stepway II and I would like to activate the cornering functions and some other controls. I have an old OBD2 Bluetooth ELM327, I tested it with the Torque app and it can easily read the instantaneous values ​​and the error codes, but on Ecutweker I can't even read it. to load the diagnosis of the ABS/ESC control unit to display the real current kilometres. everything I tried to open in the teato box returns a lot of errors. Could it be the ODB interface that sucks?

P.S. I tried from version 1.85 to 2.1 and both versions 2 and 2.1 give errors in the bluetooth connection, 1.9 and 1.85 connect to bluetooth but not to the ecu. I tried different ecu.zip databases but none worked, they all give errors

**Comment by Furtif** [comment]
duplicates issue read https://github.com/cedricp/ecutweaker/issues/5

**Comment by alex-military** [comment]
> problema duplicati leggi #5

Yes, I realized later that the Bluetooth problem was known in the new versions and I specifically tried 1.85 but even with that version I can't get any values ​​from the ecu. It gives me a correct connection and the automatic detection button keeps loading endlessly. I tried with different ecu.zips but no one can read any values. could this be a problem related to the poor quality of my obd?

**Comment by alex-military** [comment]
I would also like to point out a problem relating to Samsungs which have a "trashcan" in the file manager which holds the deleted files and the app gets the ecu.zip file from there too. If you need to replace the ecu.zip file you have to completely re-do it files even from the trash

**Comment by Furtif** [comment]
> Yes, I realized later that the Bluetooth problem was known in the new versions and I specifically tried 1.85 but even with that version I can't get any values ​​from the ecu. It gives me a correct connection and the automatic detection button keeps loading endlessly. I tried with different ecu.zips but no one can read any values. could this be a problem related to the poor quality of my obd?

possibly

**Comment by Furtif** [comment]
> I would also like to point out a problem relating to Samsungs which have a "trashcan" in the file manager which holds the deleted files and the app gets the ecu.zip file from there too. If you need to replace the ecu.zip file you have to completely re-do it files even from the trash

try zip https://github.com/cedricp/ecutweaker/issues/5#issuecomment-1946100906

put it in InternalStorage root.

**Comment by alex-military** [comment]
hello i got a new obd on amazon wifi version and it actually works. what i wanted to understand is what the automatic detection button below is for because nothing ever changes. i cant figure out how to do some things. for example i managed to set the reading from L/km to km/L. i wanted to try to activate the cornering but i tried on all the emm screens and none of them work i dont understand how i should do it. i also noticed that any screen except the abs ones and the meeter cluster ones none of them show information in the read column and the boxes in the write column are always red. am i doing something wrong or is it not communicating correctly?

the car is a sandero II stepway and in all the ecu.zip files it says that it has an emm control unit but i dont know i couldnt write anything. do you think i should try with a pc for confirmation?
