### ISSUE TITLE
In what folder application/logs/database are placed?

### ISSUE THREAD

**Issue by igogo2** [cedricp/ecutweaker#13]
I use Android 10. 
After installation i can't find the folder with application. 
In what folder i can find logs?
In what folder i should place ecu.zip?

**Comment by Furtif** [comment]
> I use Android 10. After installation i can't find the folder with application. In what folder i can find logs? In what folder i should place ecu.zip?

root storage for ecu.zip
Downloads for logs

if reply close this issue, is not a issue is a question.
thanks
